// This file was generated by Slice Machine. You may edit this file.

import * as React from "react";
import { graphql } from "gatsby";
import { PrismicRichText } from "@prismicio/react";

// TODO: Implement the TextSlice component.
//
// → Learn how to render this component with <SliceZone>
//   https://prismic.io/docs/technologies/template-slices-gatsby
export default function TextSlice({ slice }) {
  return (
    <section>
      <PrismicRichText field={slice.primary.text.richText} />
    </section>
  );
}

// TODO: Create a GraphQL fragment for each Slice variant.
//
// → Learn how to query for fields
//   https://prismic.io/docs/technologies/retrieve-fields-and-slices-gatsby
//
// → Learn how to use this GraphQL fragment
//   https://prismic.io/docs/technologies/fragments-gatsby
export const fragment = graphql`
  fragment PrismicTextDefaultSlice on PrismicTextDefaultSlice {
    slice_type
    variation
    primary {
      text {
        richText
      }
    }
  }
`;
